# Generated by Django 5.1.6 on 2026-06-01 11:48

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_bmi_options_alter_headcircumference_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Medication name (e.g., Vitamin D, Iron drops)",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "medication_type",
                    models.CharField(
                        choices=[
                            ("vitamin", "Vitamin"),
                            ("drops", "Drops"),
                            ("medicine", "Medicine"),
                            ("supplement", "Supplement"),
                            ("other", "Other"),
                        ],
                        default="vitamin",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 5 drops, 1ml, 400 IU",
                        max_length=100,
                        verbose_name="Dosage",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once_daily", "Once Daily"),
                            ("twice_daily", "Twice Daily"),
                            ("three_times_daily", "Three Times Daily"),
                            ("every_other_day", "Every Other Day"),
                            ("weekly", "Weekly"),
                            ("as_needed", "As Needed"),
                            ("custom", "Custom"),
                        ],
                        default="once_daily",
                        max_length=50,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "schedule_times",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated times (e.g., 09:00, 21:00)",
                        max_length=255,
                        verbose_name="Schedule times",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for ongoing medication",
                        null=True,
                        verbose_name="End date",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "tags",
                    core.models.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.Tagged",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medications",
                "ordering": ["-active", "name"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
        migrations.CreateModel(
            name="MedicationDose",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Time"
                    ),
                ),
                (
                    "given",
                    models.BooleanField(
                        default=True,
                        help_text="Was the medication actually given?",
                        verbose_name="Given",
                    ),
                ),
                (
                    "skipped_reason",
                    models.CharField(
                        blank=True,
                        help_text="Why was this dose skipped?",
                        max_length=255,
                        verbose_name="Skipped Reason",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_doses",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doses",
                        to="core.medication",
                        verbose_name="Medication",
                    ),
                ),
                (
                    "tags",
                    core.models.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.Tagged",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication dose",
                "verbose_name_plural": "Medication doses",
                "ordering": ["-time"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
    ]
