# Generated by Django 5.1.6 on 2026-06-22 15:29

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_medication_medicationdose"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolidFood",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="Time"
                    ),
                ),
                (
                    "food",
                    models.CharField(
                        help_text="What did the child taste? (e.g. Banana, Avocado, Rice)",
                        max_length=255,
                        verbose_name="Food",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(blank=True, null=True, verbose_name="Amount"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solid_food",
                        to="core.child",
                        verbose_name="Child",
                    ),
                ),
                (
                    "tags",
                    core.models.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.Tagged",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solid Food",
                "verbose_name_plural": "Solid Foods",
                "ordering": ["-time"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
    ]
