# Generated by Django 5.1.6 on 2026-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_solidfood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solidfood",
            name="amount",
            field=models.CharField(
                blank=True,
                help_text="A short description of how much was eaten (e.g. a spoon, a little, half a jar)",
                max_length=100,
                null=True,
                verbose_name="Amount",
            ),
        ),
    ]
